### PR TITLE
fix params bug in index method

### PR DESCRIPTION
**Pull request by kmcelwee**

### CODE REVIEW

**Review by rlskoeser — COMMENTED** [review]
The change is correct, but could you add one test case that confirms the params override works as expected in the code? (A test we should have had before, which would have failed without this correction)

**Comment by kmcelwee** [comment]
@rlskoeser This only affects the `commitWithin` parameter. Do you have a straightforward way to test if `commitWithin` was used or not? I'm not sure how I'd go about writing a test that shows that an item was indexed within a given set of time.

**Comment by rlskoeser** [comment]
> @rlskoeser This only affects the `commitWithin` parameter. Do you have a straightforward way to test if `commitWithin` was used or not? I'm not sure how I'd go about writing a test that shows that an item was indexed within a given set of time.

The best way that I know of is use a mock so you can inspect the arguments passed to the method.

**Comment by kmcelwee** [comment]
@rlskoeser I assume I'm good to merge?

**Review by rlskoeser — APPROVED** [review]

**Pull request merged**
